development:
  # origins 'localhost:3000', '127.0.0.1:3000',
  #            /\Ahttp:\/\/192\.168\.0\.\d{1,3}(:\d+)?\z/
  # Regular expressions allowed.
  origins: '*'
  resources:
    - resource: '*'
      headers: any
      methods: [get, post]
  # Make sure to include trailing /
  allowed_hosts:
    - url: 'http://localhost:8081/'
      token_lifespan_days: 1
    - url: 'http://localhost:8082/'
      token_lifespan_days: 2

test:
  origins: '*'
  resources:
    - resource: '*'
      headers: any
      methods: [get, post]
  allowed_hosts:
    - url: 'http://testintegration:8081/'
      token_lifespan_days: 3


production:
  # do not use wildcards '*' in production
  origins: 'change this'
  resources:
    - resource: 'change this'
      headers: 'change this'
      methods: ['change this']
  allowed_hosts:
    - url: 'change this'
      token_lifespan_days: 'change this'
