// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionButtonController from "./action_button_controller"
application.register("action-button", ActionButtonController)

import Activities__ExtendedDetailsController from "./activities/extended_details_controller"
application.register("activities--extended-details", Activities__ExtendedDetailsController)

import AdvancedSearchController from "./advanced_search_controller"
application.register("advanced-search", AdvancedSearchController)

import AttachmentUploadController from "./attachment_upload_controller"
application.register("attachment-upload", AttachmentUploadController)

import BreadcrumbController from "./breadcrumb_controller"
application.register("breadcrumb", BreadcrumbController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import ColourModeController from "./colour_mode_controller"
application.register("colour-mode", ColourModeController)

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import EditableCellController from "./editable_cell_controller"
application.register("editable-cell", EditableCellController)

import EmailInputController from "./email_input_controller"
application.register("email-input", EmailInputController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import Form__HiddenInputsController from "./form/hidden_inputs_controller"
application.register("form--hidden-inputs", Form__HiddenInputsController)

import Form__JsonSubmissionController from "./form/json_submission_controller"
application.register("form--json-submission", Form__JsonSubmissionController)

import Groups__RowController from "./groups/row_controller"
application.register("groups--row", Groups__RowController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import LayoutController from "./layout_controller"
application.register("layout", LayoutController)

import ListFilterController from "./list_filter_controller"
application.register("list-filter", ListFilterController)

import Metadata__FileImportController from "./metadata/file_import_controller"
application.register("metadata--file-import", Metadata__FileImportController)

import MetadataToggleController from "./metadata_toggle_controller"
application.register("metadata-toggle", MetadataToggleController)

import Nextflow__FileController from "./nextflow/file_controller"
application.register("nextflow--file", Nextflow__FileController)

import Nextflow__MetadataController from "./nextflow/metadata_controller"
application.register("nextflow--metadata", Nextflow__MetadataController)

import Nextflow__SamplesheetController from "./nextflow/samplesheet_controller"
application.register("nextflow--samplesheet", Nextflow__SamplesheetController)

import Pathogen__Datepicker__CalendarController from "./pathogen/datepicker/calendar_controller"
application.register("pathogen--datepicker--calendar", Pathogen__Datepicker__CalendarController)

import Pathogen__Datepicker__InputController from "./pathogen/datepicker/input_controller"
application.register("pathogen--datepicker--input", Pathogen__Datepicker__InputController)

import Pathogen__TabsController from "./pathogen/tabs_controller"
application.register("pathogen--tabs", Pathogen__TabsController)

import Pathogen__TooltipController from "./pathogen/tooltip_controller"
application.register("pathogen--tooltip", Pathogen__TooltipController)

import Projects__Samples__Attachments__FilesController from "./projects/samples/attachments/files_controller"
application.register("projects--samples--attachments--files", Projects__Samples__Attachments__FilesController)

import Projects__Samples__Attachments__SelectedAttachmentsController from "./projects/samples/attachments/selected_attachments_controller"
application.register("projects--samples--attachments--selected-attachments", Projects__Samples__Attachments__SelectedAttachmentsController)

import Projects__Samples__CompleteController from "./projects/samples/complete_controller"
application.register("projects--samples--complete", Projects__Samples__CompleteController)

import Projects__Samples__Metadata__CompleteController from "./projects/samples/metadata/complete_controller"
application.register("projects--samples--metadata--complete", Projects__Samples__Metadata__CompleteController)

import Projects__Samples__Metadata__CreateController from "./projects/samples/metadata/create_controller"
application.register("projects--samples--metadata--create", Projects__Samples__Metadata__CreateController)

import Projects__Samples__Metadata__DeleteListingController from "./projects/samples/metadata/delete_listing_controller"
application.register("projects--samples--metadata--delete-listing", Projects__Samples__Metadata__DeleteListingController)

import Projects__Samples__Metadata__DestroyController from "./projects/samples/metadata/destroy_controller"
application.register("projects--samples--metadata--destroy", Projects__Samples__Metadata__DestroyController)

import RefreshController from "./refresh_controller"
application.register("refresh", RefreshController)

import SearchFieldController from "./search_field_controller"
application.register("search-field", SearchFieldController)

import SelectionController from "./selection_controller"
application.register("selection", SelectionController)

import SessionstorageAmendFormController from "./sessionstorage_amend_form_controller"
application.register("sessionstorage-amend-form", SessionstorageAmendFormController)

import SidebarItemController from "./sidebar_item_controller"
application.register("sidebar-item", SidebarItemController)

import SlugifyController from "./slugify_controller"
application.register("slugify", SlugifyController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)

import SpreadsheetImportController from "./spreadsheet_import_controller"
application.register("spreadsheet-import", SpreadsheetImportController)

import TableController from "./table_controller"
application.register("table", TableController)

import TableSelectionController from "./table_selection_controller"
application.register("table-selection", TableSelectionController)

import TokenController from "./token_controller"
application.register("token", TokenController)

import TreegridController from "./treegrid_controller"
application.register("treegrid", TreegridController)

import Viral__AlertController from "./viral/alert_controller"
application.register("viral--alert", Viral__AlertController)

import Viral__DialogController from "./viral/dialog_controller"
application.register("viral--dialog", Viral__DialogController)

import Viral__DialogTriggerController from "./viral/dialog_trigger_controller"
application.register("viral--dialog-trigger", Viral__DialogTriggerController)

import Viral__DropdownController from "./viral/dropdown_controller"
application.register("viral--dropdown", Viral__DropdownController)

import Viral__FlashController from "./viral/flash_controller"
application.register("viral--flash", Viral__FlashController)

import Viral__Select2Controller from "./viral/select2_controller"
application.register("viral--select2", Viral__Select2Controller)

import Viral__SortableLists__ListController from "./viral/sortable_lists/list_controller"
application.register("viral--sortable-lists--list", Viral__SortableLists__ListController)

import Viral__SortableLists__TwoListsSelectionController from "./viral/sortable_lists/two_lists_selection_controller"
application.register("viral--sortable-lists--two-lists-selection", Viral__SortableLists__TwoListsSelectionController)

import WorkflowSelectionController from "./workflow_selection_controller"
application.register("workflow-selection", WorkflowSelectionController)
