// Import and register all your controllers

import { application } from "./application";

// Import all controllers
import ActionButtonController from "./action_button_controller.js";
import ActivitiesExtendedDetailsController from "./activities/extended_details_controller.js";
import AdvancedSearchController from "./advanced_search_controller.js";
import AttachmentUploadController from "./attachment_upload_controller.js";
import BreadcrumbController from "./breadcrumb_controller.js";
import ClipboardController from "./clipboard_controller.js";
import CollapsibleController from "./collapsible_controller.js";
import ColourModeController from "./colour_mode_controller.js";
import ConfirmationController from "./confirmation_controller.js";
import CopyController from "./copy_controller.js";
import EditableCellController from "./editable_cell_controller.js";
import EmailInputController from "./email_input_controller.js";
import FileUploadController from "./file_upload_controller.js";
import FiltersController from "./filters_controller.js";
import FormHiddenInputsController from "./form/hidden_inputs_controller.js";
import FormJsonSubmissionController from "./form/json_submission_controller.js";
import GroupsRowController from "./groups/row_controller.js";
import InfiniteScrollController from "./infinite_scroll_controller.js";
import LayoutController from "./layout_controller.js";
import ListFilterController from "./list_filter_controller.js";
import MetadataFileImportController from "./metadata/file_import_controller.js";
import MetadataToggleController from "./metadata_toggle_controller.js";
import NextflowFileController from "./nextflow/file_controller.js";
import NextflowMetadataController from "./nextflow/metadata_controller.js";
import NextflowSamplesheetController from "./nextflow/samplesheet_controller.js";
import PathogenDatepickerCalendarController from "./pathogen/datepicker/calendar_controller.js";
import PathogenDatepickerInputController from "./pathogen/datepicker/input_controller.js";
import PathogenTabsController from "./pathogen/tabs_controller.js";
import PathogenTooltipController from "./pathogen/tooltip_controller.js";
import ProjectsSamplesAttachmentsFilesController from "./projects/samples/attachments/files_controller.js";
import ProjectsSamplesAttachmentsSelectedAttachmentsController from "./projects/samples/attachments/selected_attachments_controller.js";
import ProjectsSamplesCompleteController from "./projects/samples/complete_controller.js";
import ProjectsSamplesMetadataCompleteController from "./projects/samples/metadata/complete_controller.js";
import ProjectsSamplesMetadataCreateController from "./projects/samples/metadata/create_controller.js";
import ProjectsSamplesMetadataDeleteListingController from "./projects/samples/metadata/delete_listing_controller.js";
import ProjectsSamplesMetadataDestroyController from "./projects/samples/metadata/destroy_controller.js";
import RefreshController from "./refresh_controller.js";
import SearchFieldController from "./search_field_controller.js";
import SelectionController from "./selection_controller.js";
import SessionstorageAmendFormController from "./sessionstorage_amend_form_controller.js";
import SidebarItemController from "./sidebar_item_controller.js";
import SlugifyController from "./slugify_controller.js";
import SpinnerController from "./spinner_controller.js";
import SpreadsheetImportController from "./spreadsheet_import_controller.js";
import TableController from "./table_controller.js";
import TableSelectionController from "./table_selection_controller.js";
import TokenController from "./token_controller.js";
import TreegridController from "./treegrid_controller.js";
import ViralAlertController from "./viral/alert_controller.js";
import ViralDialogController from "./viral/dialog_controller.js";
import ViralDialogTriggerController from "./viral/dialog_trigger_controller.js";
import ViralDropdownController from "./viral/dropdown_controller.js";
import ViralFlashController from "./viral/flash_controller.js";
import ViralSelect2Controller from "./viral/select2_controller.js";
import ViralSortableListsListController from "./viral/sortable_lists/list_controller.js";
import ViralSortableListsTwoListsSelectionController from "./viral/sortable_lists/two_lists_selection_controller.js";
import WorkflowSelectionController from "./workflow_selection_controller.js";

// Register controllers
application.register("action-button", ActionButtonController);
application.register("activities--extended-details", ActivitiesExtendedDetailsController);
application.register("advanced-search", AdvancedSearchController);
application.register("attachment-upload", AttachmentUploadController);
application.register("breadcrumb", BreadcrumbController);
application.register("clipboard", ClipboardController);
application.register("collapsible", CollapsibleController);
application.register("colour-mode", ColourModeController);
application.register("confirmation", ConfirmationController);
application.register("copy", CopyController);
application.register("editable-cell", EditableCellController);
application.register("email-input", EmailInputController);
application.register("file-upload", FileUploadController);
application.register("filters", FiltersController);
application.register("form--hidden-inputs", FormHiddenInputsController);
application.register("form--json-submission", FormJsonSubmissionController);
application.register("groups--row", GroupsRowController);
application.register("infinite-scroll", InfiniteScrollController);
application.register("layout", LayoutController);
application.register("list-filter", ListFilterController);
application.register("metadata--file-import", MetadataFileImportController);
application.register("metadata-toggle", MetadataToggleController);
application.register("nextflow--file", NextflowFileController);
application.register("nextflow--metadata", NextflowMetadataController);
application.register("nextflow--samplesheet", NextflowSamplesheetController);
application.register("pathogen--datepicker--calendar", PathogenDatepickerCalendarController);
application.register("pathogen--datepicker--input", PathogenDatepickerInputController);
application.register("pathogen--tabs", PathogenTabsController);
application.register("pathogen--tooltip", PathogenTooltipController);
application.register("projects--samples--attachments--files", ProjectsSamplesAttachmentsFilesController);
application.register("projects--samples--attachments--selected-attachments", ProjectsSamplesAttachmentsSelectedAttachmentsController);
application.register("projects--samples--complete", ProjectsSamplesCompleteController);
application.register("projects--samples--metadata--complete", ProjectsSamplesMetadataCompleteController);
application.register("projects--samples--metadata--create", ProjectsSamplesMetadataCreateController);
application.register("projects--samples--metadata--delete-listing", ProjectsSamplesMetadataDeleteListingController);
application.register("projects--samples--metadata--destroy", ProjectsSamplesMetadataDestroyController);
application.register("refresh", RefreshController);
application.register("search-field", SearchFieldController);
application.register("selection", SelectionController);
application.register("sessionstorage-amend-form", SessionstorageAmendFormController);
application.register("sidebar-item", SidebarItemController);
application.register("slugify", SlugifyController);
application.register("spinner", SpinnerController);
application.register("spreadsheet-import", SpreadsheetImportController);
application.register("table", TableController);
application.register("table-selection", TableSelectionController);
application.register("token", TokenController);
application.register("treegrid", TreegridController);
application.register("viral--alert", ViralAlertController);
application.register("viral--dialog", ViralDialogController);
application.register("viral--dialog-trigger", ViralDialogTriggerController);
application.register("viral--dropdown", ViralDropdownController);
application.register("viral--flash", ViralFlashController);
application.register("viral--select2", ViralSelect2Controller);
application.register("viral--sortable-lists--list", ViralSortableListsListController);
application.register("viral--sortable-lists--two-lists-selection", ViralSortableListsTwoListsSelectionController);
application.register("workflow-selection", WorkflowSelectionController);

