// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ActionButtonController from "./action_button_controller";
application.register("action-button", ActionButtonController);

import Activities__ExtendedDetailsController from "./activities/extended_details_controller";
application.register(
  "activities--extended-details",
  Activities__ExtendedDetailsController,
);

import AdvancedSearch__V1Controller from "./advanced_search/v1_controller";
application.register("advanced-search--v1", AdvancedSearch__V1Controller);

import AttachmentUploadController from "./attachment_upload_controller";
application.register("attachment-upload", AttachmentUploadController);

import BreadcrumbController from "./breadcrumb_controller";
application.register("breadcrumb", BreadcrumbController);

import ClipboardController from "./clipboard_controller";
application.register("clipboard", ClipboardController);

import CollapsibleController from "./collapsible_controller";
application.register("collapsible", CollapsibleController);

import ColourModeController from "./colour_mode_controller";
application.register("colour-mode", ColourModeController);

import Combobox__V1Controller from "./combobox/v1_controller";
application.register("combobox--v1", Combobox__V1Controller);

import ComboboxDatepicker__V1__CalendarController from "./combobox_datepicker/v1/calendar_controller";
application.register(
  "combobox-datepicker--v1--calendar",
  ComboboxDatepicker__V1__CalendarController,
);

import ComboboxDatepicker__V1__InputController from "./combobox_datepicker/v1/input_controller";
application.register(
  "combobox-datepicker--v1--input",
  ComboboxDatepicker__V1__InputController,
);

import ConfirmationController from "./confirmation_controller";
application.register("confirmation", ConfirmationController);

import CopyController from "./copy_controller";
application.register("copy", CopyController);

import Dropdown__V1Controller from "./dropdown/v1_controller";
application.register("dropdown--v1", Dropdown__V1Controller);

import Dropdown__V2Controller from "./dropdown/v2_controller";
application.register("dropdown--v2", Dropdown__V2Controller);

import EditableCellController from "./editable_cell_controller";
application.register("editable-cell", EditableCellController);

import EmailInputController from "./email_input_controller";
application.register("email-input", EmailInputController);

import ExperimentalFeatureToggleController from "./experimental_feature_toggle_controller";
application.register(
  "experimental-feature-toggle",
  ExperimentalFeatureToggleController,
);

import FileUploadController from "./file_upload_controller";
application.register("file-upload", FileUploadController);

import FiltersController from "./filters_controller";
application.register("filters", FiltersController);

import Form__JsonSubmissionController from "./form/json_submission_controller";
application.register("form--json-submission", Form__JsonSubmissionController);

import FormErrorSummaryController from "./form_error_summary_controller";
application.register("form-error-summary", FormErrorSummaryController);

import InfiniteScrollController from "./infinite_scroll_controller";
application.register("infinite-scroll", InfiniteScrollController);

import IntegrationAccessTokenController from "./integration_access_token_controller";
application.register(
  "integration-access-token",
  IntegrationAccessTokenController,
);

import LaunchWorkflowController from "./launch_workflow_controller";
application.register("launch-workflow", LaunchWorkflowController);

import LayoutController from "./layout_controller";
application.register("layout", LayoutController);

import LinelistExportController from "./linelist_export_controller";
application.register("linelist-export", LinelistExportController);

import LinelistImportController from "./linelist_import_controller";
application.register("linelist-import", LinelistImportController);

import ListInputController from "./list_input_controller";
application.register("list-input", ListInputController);

import Metadata__FileImportController from "./metadata/file_import_controller";
application.register("metadata--file-import", Metadata__FileImportController);

import MetadataToggleController from "./metadata_toggle_controller";
application.register("metadata-toggle", MetadataToggleController);

import Nextflow__V2__SamplesheetController from "./nextflow/v2/samplesheet_controller";
application.register(
  "nextflow--v2--samplesheet",
  Nextflow__V2__SamplesheetController,
);

import PersonalAccessTokensController from "./personal_access_tokens_controller";
application.register("personal-access-tokens", PersonalAccessTokensController);

import Projects__Samples__Attachments__SelectedAttachmentsController from "./projects/samples/attachments/selected_attachments_controller";
application.register(
  "projects--samples--attachments--selected-attachments",
  Projects__Samples__Attachments__SelectedAttachmentsController,
);

import Projects__Samples__CompleteController from "./projects/samples/complete_controller";
application.register(
  "projects--samples--complete",
  Projects__Samples__CompleteController,
);

import Projects__Samples__Metadata__CompleteController from "./projects/samples/metadata/complete_controller";
application.register(
  "projects--samples--metadata--complete",
  Projects__Samples__Metadata__CompleteController,
);

import Projects__Samples__Metadata__CreateController from "./projects/samples/metadata/create_controller";
application.register(
  "projects--samples--metadata--create",
  Projects__Samples__Metadata__CreateController,
);

import Projects__Samples__Metadata__DeleteListingController from "./projects/samples/metadata/delete_listing_controller";
application.register(
  "projects--samples--metadata--delete-listing",
  Projects__Samples__Metadata__DeleteListingController,
);

import Projects__Samples__Metadata__DestroyController from "./projects/samples/metadata/destroy_controller";
application.register(
  "projects--samples--metadata--destroy",
  Projects__Samples__Metadata__DestroyController,
);

import RefreshController from "./refresh_controller";
application.register("refresh", RefreshController);

import SearchFieldController from "./search_field_controller";
application.register("search-field", SearchFieldController);

import Select2__V1Controller from "./select2/v1_controller";
application.register("select2--v1", Select2__V1Controller);

import Select2__V2Controller from "./select2/v2_controller";
application.register("select2--v2", Select2__V2Controller);

import SelectionController from "./selection_controller";
application.register("selection", SelectionController);

import SessionstorageAmendFormController from "./sessionstorage_amend_form_controller";
application.register(
  "sessionstorage-amend-form",
  SessionstorageAmendFormController,
);

import SidebarItemController from "./sidebar_item_controller";
application.register("sidebar-item", SidebarItemController);

import SlugifyController from "./slugify_controller";
application.register("slugify", SlugifyController);

import SortableLists__V1__TwoListsSelectionController from "./sortable_lists/v1/two_lists_selection_controller";
application.register(
  "sortable-lists--v1--two-lists-selection",
  SortableLists__V1__TwoListsSelectionController,
);

import SpinnerController from "./spinner_controller";
application.register("spinner", SpinnerController);

import SpreadsheetImportController from "./spreadsheet_import_controller";
application.register("spreadsheet-import", SpreadsheetImportController);

import TableController from "./table_controller";
application.register("table", TableController);

import TableSelectionController from "./table_selection_controller";
application.register("table-selection", TableSelectionController);

import TokenController from "./token_controller";
application.register("token", TokenController);

import TreegridController from "./treegrid_controller";
application.register("treegrid", TreegridController);

import Viral__AlertController from "./viral/alert_controller";
application.register("viral--alert", Viral__AlertController);

import Viral__DialogController from "./viral/dialog_controller";
application.register("viral--dialog", Viral__DialogController);

import Viral__DialogTriggerController from "./viral/dialog_trigger_controller";
application.register("viral--dialog-trigger", Viral__DialogTriggerController);

import Viral__FlashController from "./viral/flash_controller";
application.register("viral--flash", Viral__FlashController);

import VisibilityFormController from "./visibility_form_controller";
application.register("visibility-form", VisibilityFormController);

import WorkflowSelectionController from "./workflow_selection_controller";
application.register("workflow-selection", WorkflowSelectionController);
