plugins:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: "3.3"
  Exclude:
    - "vendor/**/*"
    - "**/bin/**/**"
  NewCops: enable

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsmethodlength
Metrics/MethodLength:
  CountComments: false
  Max: 15

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsabcsize
Metrics/AbcSize:
  Max: 20
