# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rails', '>= 7', '< 8'

gem 'heroicons-rails', '~> 1.2'
gem 'tailwindcss-rails', '~> 3.0'
gem 'view_component', '~> 3.15'

# development dependencies
group :development do
  gem 'actioncable'
  gem 'annotate'
  gem 'listen'
  gem 'lookbook', '>= 2.3.4'
  gem 'overmind'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rails-accessibility', '~> 1.0'
end
