files:
  exclude:
    - ".devenv/**/*"
    - ".git/**/*"
    - "coverage/**/*"
    - "docs-site/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
formatter:
  enabled: true
  indentWidth: 2
  maxLineLength: 120
  rewriter:
    post: []
    pre:
      - tailwind-class-sorter
linter:
  enabled: true
version: 0.9.0
