require:
  - rubocop-rails
  - rubocop-graphql

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "**/bin/**/**"
    - "**/db/schema.rb"
    - "**/db/jobs_schema.rb"
    - "**/lib/active_storage/service/azure_storage_service.rb"
  TargetRubyVersion: "3.2"
  NewCops: enable

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsblocklength
Metrics/BlockLength:
  Exclude:
    - "**/config/environments/*.rb"
    - "**/config/routes.rb"
    - "**/config/routes/**/*.rb"
    - "**/test/**/*.rb"

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsclasslength
Metrics/ClassLength:
  Exclude:
    - "**/config/environments/*.rb"
    - "**/config/routes.rb"
    - "**/config/routes/**/*.rb"
    - "**/test/**/*.rb"

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsmodulelength
Metrics/ModuleLength:
  Exclude:
    - "**/config/routes.rb"
    - "**/config/routes/**/*.rb"
    - "**/test/**/*.rb"

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsmethodlength
Metrics/MethodLength:
  CountComments: false
  Max: 15

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsabcsize
Metrics/AbcSize:
  Max: 20

Style/RedundantConstantBase:
  Exclude:
    - "**/config/routes.rb"
    - "**/config/routes/**/*.rb"

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"

Style/Documentation:
  Exclude:
    - "test/**/*.rb"

GraphQL/ObjectDescription:
  Exclude:
    - "app/graphql/**/base_*.rb"
    - "app/graphql/resolvers/**/*.rb"
    - "test/**/*.rb"
