export const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

export const CALENDAR_CLASSES = {
  SELECTED_DATE: [
    "bg-primary-700",
    "!text-white",
    "hover:bg-primary-800",
    "dark:text-white",
    "dark:bg-primary-600",
    "dark:hover:bg-primary-700",
    "dark:border-primary-900",
    "dark:hover:bg-primary-700",
    "cursor-pointer",
  ],
  IN_MONTH: [
    "not-aria-disabled:text-slate-900",
    "not-aria-disabled:hover:bg-slate-100",
    "not-aria-disabled:cursor-pointer",
    "not-aria-disabled:text-slate-900",
    "not-aria-disabled:hover:bg-slate-100",
    "aria-disabled:cursor-not-allowed",
    "aria-disabled:text-slate-500",
    "aria-disabled:line-through",
    "not-aria-disabled:dark:text-white",
    "not-aria-disabled:dark:hover:bg-slate-600",
    "aria-disabled:dark:text-slate-300",
  ],
  OUT_OF_MONTH: [
    "not-aria-disabled:cursor-pointer",
    "not-aria-disabled:text-slate-500",
    "not-aria-disabled:hover:bg-slate-100",
    "aria-disabled:cursor-not-allowed",
    "aria-disabled:text-slate-500",
    "aria-disabled:line-through",
    "not-aria-disabled:dark:text-slate-300",
    "not-aria-disabled:dark:hover:bg-slate-600",
    "aria-disabled:dark:text-slate-300",
  ],
  TODAYS_DATE: [
    "after:absolute",
    "after:left-1/2",
    "after:bottom-1",
    "after:h-1.5",
    "after:w-1.5",
    "after:-translate-x-1/2",
    "after:rounded-full",
    "after:bg-primary-700",
    "dark:after:bg-primary-600",
    "after:content-['']",
  ],

  TODAYS_HOVER: ["hover:bg-slate-200", "dark:hover:bg-slate-500"],
  MONTH_NAV_ARROW_DISABLED: ["text-slate-400", "dark:text-slate-500"],
  MONTH_NAV_ARROW_ENABLED: ["text-slate-900", "dark:text-slate-100"],
};
