#!/bin/bash

export INPUT_TYPE=$1

build_css() {
  # Get a list of all the CSS files in the src directory
  npx tailwindcss -i ./app/assets/styles/input.css -o ./app/assets/styles/output.css
}

echo "Building CSS assets..."
build_css
