require:
  - rubocop-rails

AllCops:
  NewCops: enable

Lint/MissingSuper:
  Exclude:
   - "app/components/**/*.rb"

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsmethodlength
Metrics/MethodLength:
  CountComments: false
  Max: 15


