# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# Available providers: developer, saml, azure_activedirectory_v2
OMNIAUTH_MODES: ['developer', 'azure_activedirectory_v2']

AZURE_CLIENT_ID: some-id
AZURE_CLIENT_SECRET: some-secret-0Ru8cEB

IDP_CERT_FINGERPRINT: some-fingerprint-value
IDP_SSO_SERVICE_URL: some-sso-service-url
