user_opt_in_features:
  data_grid_samples_table:
    allowlist: [user1@email.com]
    description:
      en: "Enable the new data grid for the samples table."
      fr: "Activer la nouvelle grille de données pour le tableau d'échantillons."
    name:
      en: "Data Grid Samples Table"
      fr: "Tableau de données"
