export const FIELD_CLASSES = {
  ERROR: [
    "bg-slate-50",
    "border",
    "border-red-500",
    "text-slate-900",
    "text-sm",
    "rounded-lg",
    "block",
    "w-full",
    "p-2.5",
    "dark:bg-slate-700",
    "dark:border-slate-600",
    "dark:placeholder-slate-400",
    "dark:text-white",
  ],
  ERROR_SPAN: ["text-red-500"],
  VALID: [
    "bg-slate-50",
    "border",
    "border-slate-300",
    "text-slate-900",
    "text-sm",
    "rounded-lg",
    "block",
    "w-full",
    "p-2.5",
    "dark:bg-slate-700",
    "dark:border-slate-600",
    "dark:placeholder-slate-400",
    "dark:text-white",
  ],
};
