development:
  omniauth_providers: []
  # developer_text:
  # developer_icon:
  # saml_text:
  # saml_icon:
  # entra_id_text:
  # entra_id_icon:

test:
  omniauth_providers: [developer, saml, entra_id]
  # developer_text:
  # developer_icon:
  # saml_text:
  # saml_icon:
  # entra_id_text:
  # entra_id_icon:

production:
  omniauth_providers: []
  # saml_text:
  # saml_icon:
  # entra_id_text:
  # entra_id_icon:
