name: trigger-azure-devops

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'phac-nml'
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
          azure-devops-project-url: ${{ secrets.PROJECT_URL }}
          # Name of the Azure Pipline to be triggered
          azure-pipeline-name: ${{ secrets.PIPELINE_NAME }}
          # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
          azure-devops-token: ${{ secrets.DEVOPS_PAT }}
