# frozen_string_literal: true

require 'application_system_test_case'

class ProjectsTest < ApplicationSystemTestCase
  def setup
    @user = users(:john_doe)
    login_as @user
  end

  test 'can create a project' do
    new_project_name = 'Project 1'
    visit new_project_path

    assert_selector 'h1', text: I18n.t(:'projects.new.title'), count: 1

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      fill_in 'Name', with: new_project_name
      fill_in I18n.t('projects.new.select_namespace'), with: 'USR'
      find('ul li', text: 'INXT_USR_AAAAAAAAAA').click
      click_on I18n.t(:'projects.new.submit')
    end
    assert_selector 'h1', text: new_project_name

    assert_text I18n.t(:'projects.create.success', project_name: new_project_name)
    new_project = @user.namespace.project_namespaces.find_by(name: new_project_name).project
    assert_current_path(namespace_project_path(new_project.parent, new_project))
  end

  test 'should have Project URL filled with user namespace, when creating a new project using the nav bar' do
    visit dashboard_projects_url

    trigger = find('#sidebar-new-dropdown-trigger')
    trigger.hover
    assert_selector '#sidebar-new-dropdown-trigger-tooltip[data-state="open"]'

    trigger.click
    assert_selector '#sidebar-new-dropdown-trigger-tooltip[data-state="closed"]', visible: :all
    click_link I18n.t('general.navbar.new_dropdown.project')

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      assert_selector %(input[data-select2--v1-target="input"]) do |input|
        assert_equal @user.namespace.full_path, input['value']
      end
    end
  end

  test 'should have Project URL filled with the parent group, when creating a new project from within a group' do
    group1 = groups(:group_one)
    visit group_url(group1)
    click_link I18n.t('groups.show.create_project_button')

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      assert_selector %(input[data-select2--v1-target="input"]) do |input|
        assert_equal group1.path, input['value']
      end
    end
  end

  test 'project path is autogenerated from project name' do
    project_name = 'TESTtest'

    visit dashboard_projects_url

    click_on I18n.t(:'dashboard.projects.index.create_project_button')

    assert_selector 'h1', text: I18n.t(:'projects.new.title')

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      fill_in I18n.t(:'activerecord.attributes.namespaces/project_namespace.name'), with: project_name
      fill_in I18n.t('projects.new.select_namespace'), with: 'USR'
      find('ul li', text: 'INXT_USR_AAAAAAAAAA').click
      assert_equal 'testtest',
                   find_field(I18n.t(:'activerecord.attributes.namespaces/project_namespace.path')).value
      click_on I18n.t(:'projects.new.submit')
    end

    assert_selector 'h1', text: project_name
    new_project = @user.namespace.project_namespaces.find_by(name: project_name).project
    assert_current_path(namespace_project_path(new_project.parent, new_project))
  end

  test 'invalid nested project create focuses the summary and namespace link' do
    visit new_project_path

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      fill_in 'Name', with: 'New Project'
      fill_in 'Path', with: 'new-project'
      page.execute_script <<~JS
        const namespaceField = document.querySelector('[name="project[namespace_attributes][parent_id]"]');
        if (namespaceField) {
          namespaceField.value = "";
          namespaceField.dispatchEvent(new Event("change", { bubbles: true }));
        }
      JS
      click_on I18n.t(:'projects.new.submit')
    end

    assert_selector 'turbo-frame#project_form [data-controller="form-error-summary"]', focused: true
    assert_selector '#project_namespace_attributes_namespace_error',
                    text: I18n.t('services.projects.create.namespace_required')

    within 'turbo-frame#project_form [data-controller="form-error-summary"]' do
      click_link I18n.t('services.projects.create.namespace_required')
    end

    assert_selector '#namespace-select', focused: true
    click_on I18n.t(:'projects.new.submit')
    assert_selector 'turbo-frame#project_form [data-controller="form-error-summary"]', focused: true
    assert_selector 'button[type=submit]:not(:disabled)', text: I18n.t(:'projects.new.submit')
    assert_accessible
  end
end
