# frozen_string_literal: true

require 'application_system_test_case'

class ProjectsTest < ApplicationSystemTestCase
  def setup
    @user = users(:john_doe)
    login_as @user
  end

  test 'project path is autogenerated from project name' do
    project_name = 'TESTtest'

    visit dashboard_projects_url

    click_on I18n.t(:'dashboard.projects.index.create_project_button')

    assert_selector 'h1', text: I18n.t(:'projects.new.title')

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      fill_in I18n.t(:'activerecord.attributes.namespaces/project_namespace.name'), with: project_name
      fill_in I18n.t('projects.new.select_namespace'), with: 'USR'
      find('ul li', text: 'INXT_USR_AAAAAAAAAA').click
      assert_equal 'testtest',
                   find_field(I18n.t(:'activerecord.attributes.namespaces/project_namespace.path')).value
      click_on I18n.t(:'projects.new.submit')
    end

    assert_selector 'h1', text: project_name
    new_project = @user.namespace.project_namespaces.find_by(name: project_name).project
    assert_current_path(namespace_project_path(new_project.parent, new_project))
  end

  test 'invalid nested project create focuses the summary and namespace link' do
    visit new_project_path

    within %(div[data-controller="slugify"][data-controller-connected="true"]) do
      fill_in 'Name', with: 'New Project'
      fill_in 'Path', with: 'new-project'
      page.execute_script <<~JS
        const namespaceField = document.querySelector('[name="project[namespace_attributes][parent_id]"]');
        if (namespaceField) {
          namespaceField.value = "";
          namespaceField.dispatchEvent(new Event("change", { bubbles: true }));
        }
      JS
      click_on I18n.t(:'projects.new.submit')
    end

    assert_selector 'turbo-frame#project_form [data-controller="form-error-summary"]', focused: true
    assert_selector '#project_namespace_attributes_namespace_error',
                    text: I18n.t('services.projects.create.namespace_required')

    within 'turbo-frame#project_form [data-controller="form-error-summary"]' do
      click_link I18n.t('services.projects.create.namespace_required')
    end

    assert_selector '#namespace-select', focused: true
    click_on I18n.t(:'projects.new.submit')
    assert_selector 'turbo-frame#project_form [data-controller="form-error-summary"]', focused: true
    assert_selector 'button[type=submit]:not(:disabled)', text: I18n.t(:'projects.new.submit')
    assert_accessible
  end
end
